services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=banking'
      - 'POSTGRES_PASSWORD=sql'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_VHOST=/'
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
