services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=banking'
      - 'POSTGRES_PASSWORD=sql'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_VHOST=/'
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
  bankingapp:
    build:
      context: bankingapp
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sql
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=myuser
      - SPRING_RABBITMQ_PASSWORD=secret

